site_name: 'test2'
site_description: 'Main documentation for the test2'
repo_url: https://github.com/DaggupatiPavan-1/test2
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'index.md'

